# Generated by Django 3.2.11 on 2022-02-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAliyunConfig',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_num', models.CharField(default='', max_length=11)),
                ('pwd_home', models.CharField(default='', max_length=500)),
                ('hostname', models.CharField(default='', max_length=100)),
                ('logname', models.CharField(default='', max_length=50)),
                ('platfrom', models.CharField(default='', max_length=20)),
                ('learnsome', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAliyunOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('command_time', models.DateTimeField()),
                ('command_content', models.CharField(default='', max_length=100)),
                ('command_catalog', models.CharField(default='', max_length=100)),
                ('command_result', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
