# Generated by Django 3.2.11 on 2022-03-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandGather',
            fields=[
                ('command_id', models.AutoField(primary_key=True, serialize=False)),
                ('command_data', models.CharField(default='', max_length=1000)),
                ('command_updatatime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentCommandGather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_command', models.IntegerField()),
                ('student_command_data', models.IntegerField()),
                ('student_iphone', models.CharField(default='', max_length=11)),
                ('student_request_time', models.DateTimeField()),
                ('student_response_time', models.DateTimeField()),
            ],
        ),
    ]
