# Generated by Django 3.2.11 on 2022-03-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_commandgather_studentcommandgather'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcommandgather',
            name='student_command_ok',
            field=models.IntegerField(default=0),
        ),
    ]
