# Generated by Django 3.2.11 on 2022-03-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_studentcommandgather_student_command_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcommandgather',
            name='student_command_data',
            field=models.IntegerField(default=0),
        ),
    ]
