# Generated by Django 3.2.11 on 2022-03-25 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_studentcommandgather_student_command_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandgather',
            name='command_updatatime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='studentcommandgather',
            name='student_request_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='studentcommandgather',
            name='student_response_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
